[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title = "ORBIT Environments contributed by the community."
description="Extension containing environments for robot learning contributed by the community."
readme  = "docs/README.md"
repository = "https://github.com/NVIDIA-Omniverse/Orbit"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_tasks" = {}
"omni.isaac.core" = {}
"omni.isaac.gym" = {}
"omni.replicator.isaac" = {}

[[python.module]]
name = "omni.isaac.contrib_tasks"
