# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

params:
  seed: 42

  # environment wrapper clipping
  env:
    clip_observations: 100.0
    clip_actions: 100.0
    obs_groups:
      obs: ["policy", "proprio", "base_image", "wrist_image"]
      states: ["policy", "proprio", "perception"]
    concate_obs_groups: False

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: encoder_actor_critic
    separate: True
    encoders:
      encoder_cfgs:
        depth_image1:
          class_type: CNN
          encoding_groups: ["base_image"]
          channels: [32, 64, 128]
          kernel_sizes: [3, 3, 3]
          strides: [2, 2, 2]
          paddings: [1, 1, 1]
          use_maxpool: True
          pool_size: 2
          activation: elu
          transpose: True
        depth_image2:
          class_type: CNN
          encoding_groups: ["wrist_image"]
          channels: [32, 64, 128]
          kernel_sizes: [3, 3, 3]
          strides: [2, 2, 2]
          paddings: [1, 1, 1]
          use_maxpool: True
          pool_size: 2
          activation: elu
          transpose: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: reorient
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: False
    num_actors: -1
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-3
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.01
    score_to_win: 100000000
    max_epochs: 750000
    save_best_after: 100
    save_frequency: 50
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.001
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 8192
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    clip_actions: False
    seq_len: 4
    bounds_loss_coef: 0.0001
    central_value_config:
      minibatch_size: 8192
      mini_epochs: 4
      learning_rate: 1e-3
      kl_threshold: 0.01
      clip_value: True
      normalize_input: True
      truncate_grads: True

      network:
        name: encoder_actor_critic
        central_value: True
        encoder_cfgs:
        mlp:
          units: [512, 256, 128]
          activation: elu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None
