# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Joint names in the target physics engine where policy is deployed (e.g., Newton/MJWarp)
target_joint_names:
  - "left_hip_pitch_joint"
  - "left_hip_roll_joint"
  - "left_hip_yaw_joint"
  - "left_knee_joint"
  - "left_ankle_pitch_joint"
  - "left_ankle_roll_joint"
  - "right_hip_pitch_joint"
  - "right_hip_roll_joint"
  - "right_hip_yaw_joint"
  - "right_knee_joint"
  - "right_ankle_pitch_joint"
  - "right_ankle_roll_joint"
  - "torso_joint"
  - "left_shoulder_pitch_joint"
  - "left_shoulder_roll_joint"
  - "left_shoulder_yaw_joint"
  - "left_elbow_pitch_joint"
  - "left_elbow_roll_joint"
  - "left_five_joint"
  - "left_six_joint"
  - "left_three_joint"
  - "left_four_joint"
  - "left_zero_joint"
  - "left_one_joint"
  - "left_two_joint"
  - "right_shoulder_pitch_joint"
  - "right_shoulder_roll_joint"
  - "right_shoulder_yaw_joint"
  - "right_elbow_pitch_joint"
  - "right_elbow_roll_joint"
  - "right_five_joint"
  - "right_six_joint"
  - "right_three_joint"
  - "right_four_joint"
  - "right_zero_joint"
  - "right_one_joint"
  - "right_two_joint"

# Joint names in the source physics engine where policy is trained (e.g., PhysX)
source_joint_names:
  - "left_hip_pitch_joint"
  - "right_hip_pitch_joint"
  - "torso_joint"
  - "left_hip_roll_joint"
  - "right_hip_roll_joint"
  - "left_shoulder_pitch_joint"
  - "right_shoulder_pitch_joint"
  - "left_hip_yaw_joint"
  - "right_hip_yaw_joint"
  - "left_shoulder_roll_joint"
  - "right_shoulder_roll_joint"
  - "left_knee_joint"
  - "right_knee_joint"
  - "left_shoulder_yaw_joint"
  - "right_shoulder_yaw_joint"
  - "left_ankle_pitch_joint"
  - "right_ankle_pitch_joint"
  - "left_elbow_pitch_joint"
  - "right_elbow_pitch_joint"
  - "left_ankle_roll_joint"
  - "right_ankle_roll_joint"
  - "left_elbow_roll_joint"
  - "right_elbow_roll_joint"
  - "left_five_joint"
  - "left_three_joint"
  - "left_zero_joint"
  - "right_five_joint"
  - "right_three_joint"
  - "right_zero_joint"
  - "left_six_joint"
  - "left_four_joint"
  - "left_one_joint"
  - "right_six_joint"
  - "right_four_joint"
  - "right_one_joint"
  - "left_two_joint"
  - "right_two_joint"
