# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Joint names in the target physics engine where policy is deployed (e.g., Newton/MJWarp)
target_joint_names:
  - "left_hip_yaw"
  - "left_hip_roll"
  - "left_hip_pitch"
  - "left_knee"
  - "left_ankle"
  - "right_hip_yaw"
  - "right_hip_roll"
  - "right_hip_pitch"
  - "right_knee"
  - "right_ankle"
  - "torso"
  - "left_shoulder_pitch"
  - "left_shoulder_roll"
  - "left_shoulder_yaw"
  - "left_elbow"
  - "right_shoulder_pitch"
  - "right_shoulder_roll"
  - "right_shoulder_yaw"
  - "right_elbow"

# Joint names in the source physics engine where policy is trained (e.g., PhysX)
source_joint_names:
  - "left_hip_yaw"
  - "right_hip_yaw"
  - "torso"
  - "left_hip_roll"
  - "right_hip_roll"
  - "left_shoulder_pitch"
  - "right_shoulder_pitch"
  - "left_hip_pitch"
  - "right_hip_pitch"
  - "left_shoulder_roll"
  - "right_shoulder_roll"
  - "left_knee"
  - "right_knee"
  - "left_shoulder_yaw"
  - "right_shoulder_yaw"
  - "left_ankle"
  - "right_ankle"
  - "left_elbow"
  - "right_elbow"
