[package]
# Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title =  "Isaac Lab MultiRotor Implementation"
description="Extension containing implementation for multi rotor systems"
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["kit", "robotics", "assets", "isaaclab"]

[dependencies]
"isaaclab" = {}

[core]
reloadable = false

# Main python module this extension provides.
[[python.module]]
name = "isaaclab_multirotor"
