[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title = "Experimental environments for IsaacLab"
description="Extension containing suite of experimental environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}

[core]
reloadable = false

[[python.module]]
name = "isaaclab_tasks.experimental"
