[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.5.3"

# Description
title = "ORBIT Environments"
description="Extension containing suite of environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/NVIDIA-Omniverse/Orbit"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_assets" = {}
"omni.isaac.core" = {}
"omni.isaac.gym" = {}
"omni.replicator.isaac" = {}

[[python.module]]
name = "omni.isaac.orbit_tasks"
