[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.15.11"

# Description
title = "ORBIT framework for Robot Learning"
description="Extension providing main framework interfaces and abstractions for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/NVIDIA-Omniverse/Orbit"
category = "robotics"
keywords = ["kit", "robotics", "learning", "ai"]

[dependencies]
"omni.isaac.core" = {}
"omni.replicator.core" = {}

[[python.module]]
name = "omni.isaac.orbit"
